import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import UserContextProvider from '@/components/Providers/UserProvider';
import { getCurrentUser } from '@/lib/session';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const user = await getCurrentUser();

    return (
        <html lang="en">
            <body className={inter.className}>
                <UserContextProvider user={user}>
                    {children}
                </UserContextProvider>
            </body>
        </html>
    );
}
