# Generated by Django 4.2.3 on 2023-07-24 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_phoneverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 4, 10, 23, 799029, tzinfo=datetime.timezone.utc)),
        ),
    ]
