# Generated by Django 4.2.3 on 2023-07-24 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_phone_verified_user_phone_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 19, 4, 53, 963991, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2023, 7, 24, 19, 4, 53, 964449, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
