# Generated by Django 4.2.3 on 2023-07-24 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverificationtoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 20, 1, 50, 259700, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 20, 1, 50, 259204, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='token',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
