# Generated by Django 4.2.3 on 2023-07-25 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_phoneverificationtoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 5, 46, 11, 326096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 5, 46, 11, 325701, tzinfo=datetime.timezone.utc)),
        ),
    ]
