# Generated by Django 4.2.3 on 2023-07-26 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_emailverificationtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 21, 37, 56, 745412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 21, 37, 56, 744958, tzinfo=datetime.timezone.utc)),
        ),
    ]
